#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2014--, The Qiita Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import click

from qp_deblur.deblur import generate_tree_from_fragments

@click.command()
@click.option('--fp_fragments', required=True, type=str)
@click.option('--output_dir', required=True, type=str)
#execute needed to support click
def execute(fp_fragments, output_dir):
    """Generates a tree from fragments and puts the output in output_dir"""
    print(fp_fragments)
    print(output_dir)
    #status, message = generate_tree_from_fragments(fp_fragments, output_dir)
    status = False
    message = 'fp'
    if status:
        print(message)  # message will be fp of output tree
        #if successful, script will automatically return status code 0.
    else:
        # message will be exception string
        print("An error occured: %s" % message)
        #ensure that script returns status code 1, if an error occured.
        exit(1)

if __name__ == '__main__':
    execute()

