#!/usr/bin/env python

# -----------------------------------------------------------------------------
# Copyright (c) 2014--, The Qiita Development Team.
#
# Distributed under the terms of the BSD 3-clause License.
#
# The full license is in the file LICENSE, distributed with this software.
# -----------------------------------------------------------------------------

import click

from qp_deblur.deblur import remove_unmatched_fragments_from_biom

@click.command()
@click.option('--fp_phylogeny', required=True, type=str)
@click.option('--fp_biom', required=True, type=str)

#execute needed to support click
def execute(fp_phylogeny, fp_biom):
    """Filters observations from fp_biom that are not found in fp_phylogeny"""
    status, message = remove_unmatched_fragments_from_biom(fp_phylogeny, fp_biom)

    if status:
        print(message)  # message will be fp of output biom
        #if successful, script will automatically return status code 0.
    else:
        # message will be exception string
        print("An error occured: %s" % message)
        #ensure that script returns status code 1, if an error occured.
        exit(1)

if __name__ == '__main__':
    execute()